import fs from 'node:fs'
import path from 'node:path'
import { NextResponse } from 'next/server'
import { getDb, SCREENSHOT_DIR } from '@/lib/db'
import { notFound, requireUser } from '@/lib/auth/require'

export const runtime = 'nodejs'

/**
 * Screenshots are deliberately outside `public/` — they contain whatever was on
 * screen while a scenario ran, including a signed-in view of someone's site.
 * Serving them by hand is what lets every read be checked against the owner.
 *
 * Paths arrive as ["maps"|"runs", <jobId>, <file>].
 */
export async function GET(
  _request: Request,
  { params }: { params: Promise<{ path: string[] }> },
) {
  const { user, response } = await requireUser()
  if (response) return response

  const segments = (await params).path ?? []
  if (segments.length !== 3) return notFound()

  const [kind, jobId, file] = segments

  if (kind !== 'maps' && kind !== 'runs') return notFound()
  // Identifiers and filenames are generated by us and always match this shape;
  // anything else is an attempt to climb out of the screenshot directory.
  if (!/^[a-f0-9]{24}$/.test(jobId)) return notFound()
  if (!/^[a-zA-Z0-9._-]+\.jpg$/.test(file) || file.includes('..')) return notFound()

  const table = kind === 'maps' ? 'maps' : 'runs'
  const owned = getDb()
    .prepare(`SELECT 1 FROM ${table} WHERE id = ? AND user_id = ?`)
    .get(jobId, user.id)
  if (!owned) return notFound()

  const target = path.join(SCREENSHOT_DIR, kind, jobId, file)

  // Belt and braces: even with the checks above, never serve a resolved path
  // that escapes the screenshot root.
  const root = path.resolve(SCREENSHOT_DIR)
  if (!path.resolve(target).startsWith(root + path.sep)) return notFound()

  let data: Buffer
  try {
    data = await fs.promises.readFile(target)
  } catch {
    return notFound()
  }

  return new NextResponse(new Uint8Array(data), {
    headers: {
      'content-type': 'image/jpeg',
      'content-length': String(data.length),
      // Private: a shared cache must never hand one account's screenshot to another.
      'cache-control': 'private, max-age=3600',
    },
  })
}
